### ISSUE TITLE
Aggregator with bus-serialbattery

### ISSUE THREAD

**Issue by seamaster101** [pulquero/DCSystemAggregator#1]
I have JK-BMS with bus serial battery install. At the moment I'm testing on the bench with single BMS which data (battery voltage, current, temperature, etc) I can see on the Venus OS (running on RPI4) screen. I installed DCSystemAggregator hoping that i can see the combined values of multiple batteries that are connected in parallel in the same bank but equipped with their own BMS each.
With one battery and BMS installed i don't see the aggregator showing me voltage of the battery. Is that how it suppose to work? does it expect to see multiple BMSs sending voltage and only then displaying the average?

**Comment by pulquero** [comment]
Currently, it registers a 'dcsystem' device that aggregates devices that report themselves as 'dcloads' or 'dcsources'. I suspect your bms' report as type 'battery'. I might be able to extend it to include batteries, though the bigger issue is how to represent the aggregated batteries to Venus. Can you include some screenshots of dbus-spy, so I can see how these bms' appear in Venus?

**Comment by seamaster101** [comment]
Thank you, I will do that with pleasure, but excuse my ignorance - how do I install/run bus-spy?

**Comment by pulquero** [comment]
Log in to your Pi using ssh (https://www.victronenergy.com/live/ccgx:root_access), and run 'dbus-spy'.

**Comment by seamaster101** [comment]
Here is what I got:

Alarms/CellImbalance                                                            0
Alarms/HighCellVoltage                                                          -
Alarms/HighChargeCurrent                                                        0
Alarms/HighChargeTemperature                                                    0
Alarms/HighDischargeCurrent                                                     0
Alarms/HighTemperature                                                          0
Alarms/HighVoltage                                                              0
Alarms/InternalFailure                                                          -
Alarms/LowCellVoltage                                                           0
Alarms/LowChargeTemperature                                                     0
Alarms/LowSoc                                                                   0
Alarms/LowTemperature                                                           0
Alarms/LowVoltage                                                               0
Balances/Cell1                                                                  0
Balances/Cell2                                                                  0
Balances/Cell3                                                                  0
Balances/Cell4                                                                  0
Balancing                                                                       0
Capacity                                                                     37.2
Connected                                                                       1
ConsumedAmphours                                                              2.8
CustomName                                                   SerialBattery(Jkbms)
Dc/0/Current                                                                    0
Dc/0/MidVoltage                                                                 -
Dc/0/MidVoltageDeviation                                                        -
Dc/0/Power                                                                      0
Dc/0/Temperature                                                               22
Dc/0/Voltage                                                                13.32
DeviceInstance                                                                  1
FirmwareVersion                                                            0.14.3
HardwareVersion                                                     JKBMS 4 cells
Info/BatteryLowVoltage                                                       11.6
Info/MaxChargeCurrent                                                          25
Info/MaxChargeVoltage                                                        13.8
Info/MaxDischargeCurrent                                                       60
InstalledCapacity                                                              40
Io/AllowToCharge                                                                1
Io/AllowToDischarge                                                             1
Mgmt/Connection                                               Serial /dev/ttyUSB0
Mgmt/ProcessName              /opt/victronenergy/dbus-serialbattery/dbushelper.py
Mgmt/ProcessVersion                                                 Python 3.8.13
ProductId                                                                       0
ProductName                                                  SerialBattery(Jkbms)
Soc                                                                            93
System/MaxCellTemperature                                                      22
System/MaxCellVoltage                                                       3.423
System/MaxVoltageCellId                                                        C4
System/MinCellTemperature                                                      22
System/MinCellVoltage                                                       3.172
System/MinVoltageCellId                                                        C2
System/NrOfCellsPerBattery                                                      4
System/NrOfModulesBlockingCharge                                                0
System/NrOfModulesBlockingDischarge                                             0
System/NrOfModulesOffline                                                       0
System/NrOfModulesOnline                                                        1
Voltages/Cell1                                                              3.409
Voltages/Cell2                                                              3.172
Voltages/Cell3                                                              3.317
Voltages/Cell4                                                              3.423
Voltages/Diff                                                               0.251
Voltages/Sum                                                               13.321

**Comment by pulquero** [comment]
Thanks, and what's the dbus address on the main screen?

**Comment by seamaster101** [comment]
I guess you will probably have to apply similar logic that you have in the current aggregator:- average all reporting BMSs voltages, add all BMSs currents, "cell differential in the battery" and possible another field "cell differential in the bank"

**Comment by seamaster101** [comment]
com.victronenergy.battery.ttyUSB0 
<img width="578" alt="image" src="https://user-images.githubusercontent.com/7897023/215360767-5ce6821c-14e8-4c45-8f9f-89e0136d0ff9.png">

**Comment by pulquero** [comment]
Thanks, I think you need to see what happens with 2 batteries connected. I believe there is/will appear a setting in the venus UI to select which battery to use. If this is the case, then I can write a battery aggregator.

**Comment by seamaster101** [comment]
Actually with 2 batteries connected, the second one will be reporting on com.victronenergy.battery.ttyUSB1 so both will be displayed. I don't have multiple battery setup at the moment and it is little cumbersome to setup on the desk for testing, but I believe the bus-serialbattery will display them both 

![](https://user-images.githubusercontent.com/2902641/148074673-311e4b9f-6e3c-4943-a420-b84e71d5d01c.jpeg)

**Comment by pulquero** [comment]
OK, I'll see what I can put together.

**Comment by pulquero** [comment]
Please checkout https://github.com/pulquero/BatteryAggregator.

**Comment by seamaster101** [comment]
How do I install it? it does not show up in SetupHelper. When I manually added it it does not find it

**Comment by pulquero** [comment]
sry, forgot the 'latest' tag. Try it again.

**Comment by seamaster101** [comment]
Still couldn’t do it:

It appears does not find it. No version shows available on GitHub field.
Also if I try to add the tag when I’m. describing it in Inactive packages in SetupHelper, the tag is to long to fit in the field and gets truncated, therefore i need to enter the branch name BatteryAggregator. What am I doing wrong?

**Comment by pulquero** [comment]
Another option is to look in /data/SetupHelper and modify defaultPackageList, eg: https://github.com/pulquero/SetupHelper/blob/main/defaultPackageList.

**Comment by seamaster101** [comment]
This did it. I successfully installed it and it shows values as expected. 
Thank you very much! this is Awesome!
Some observations from quick testing: 
I thought I will be able to select the BatteryAggregator to be my Battery Monitor, but it does not show up on the list.
instead I still see the data from the BMS there 




But i see it on this page:


Also i noted the aggregator is not available as an option to select to use in the VRM


I will keep testing and reporting if you don't mind.
I’m waiting for some connectors to come from Aliexpress to be able to connect to the BMSs and then I will try with multiple BMS and report the results
 
Jordan

**Comment by pulquero** [comment]
Sure, and if you want any extra aggregated values adding, let me know. It might not be available, because I'm missing some key value. I'll dig deeper, too.

**Comment by pulquero** [comment]
Being able to select the aggregator should now work (v1.1).

**Comment by seamaster101** [comment]
I did new install on docent RPI for testing.
it installed ok after in /data/SetupHelper I modified defaultPackageList


but for some reason it is not picking up the values from SerialBattery(jkbms)
did i miss some step in the setup?





Jordan

**Comment by pulquero** [comment]
Run "cat /var/log/BatteryAggregator/current" to check for errors in the log. Also, try reinstalling it from the command line "/data/BatteryAggregator/setup".

**Comment by seamaster101** [comment]
@4000000063dc1112353383b4 BatteryAggregator/setup: installing BatteryAggregator service - please wait
@4000000063dc111c22fa5a74 INFO:root:registered ourselves on D-Bus as com.victronenergy.battery.aggregator
@4000000063dc111c24f8f164 INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
@4000000063dc111c254e607c INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB0, scanning and storing items
@4000000063dc111c25813fec INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB0 has device instance 1
@4000000063dc111c2688e034 INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
@4000000063dc111c269f236c INFO:battery:Registered Battery Aggregator
@4000000063dc111c35d31f14 Traceback (most recent call last):
@4000000063dc111c35d33a6c   File "/data/BatteryAggregator/battery_service.py", line 217, in publish
@4000000063dc111c35d34a0c     self.update()
@4000000063dc111c35d351dc   File "/data/BatteryAggregator/battery_service.py", line 183, in update
@4000000063dc111c35d3617c     maxLowVoltage = _safe_max(maxLowVoltage, lowVoltage)
@4000000063dc111c35d3711c   File "/data/BatteryAggregator/battery_service.py", line 70, in _safe_max
@4000000063dc111c35d384a4     return max(newValue, currentValue) if currentValue else newValue
@4000000063dc111c35d4f3d4 TypeError: '>' not supported between instances of 'float' and 'NoneType'
@4000000063dc111c3b45e1ac BatteryAggregator/setup: adding BatteryAggregator/setup to reinstallScriptsList
@4000000063dc111d0407de34 BatteryAggregator/setup: completed
***@***.***:~#

**Comment by seamaster101** [comment]
Device is reading one BMS but aggregatebattery shows 0. Also the Autoselect picks up aggregator now automatically not the BMS as it use to do before. This is actually good if aggregator was reading correct, but at the moment it appears to have some issue 

here is the log:
@4000000063dc1112353383b4 BatteryAggregator/setup: installing BatteryAggregator service - please wait
@4000000063dc111c22fa5a74 INFO:root:registered ourselves on D-Bus as com.victronenergy.battery.aggregator
@4000000063dc111c24f8f164 INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
@4000000063dc111c254e607c INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB0, scanning and storing items
@4000000063dc111c25813fec INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB0 has device instance 1
@4000000063dc111c2688e034 INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
@4000000063dc111c269f236c INFO:battery:Registered Battery Aggregator
@4000000063dc111c35d31f14 Traceback (most recent call last):
@4000000063dc111c35d33a6c   File "/data/BatteryAggregator/battery_service.py", line 217, in publish
@4000000063dc111c35d34a0c     self.update()
@4000000063dc111c35d351dc   File "/data/BatteryAggregator/battery_service.py", line 183, in update
@4000000063dc111c35d3617c     maxLowVoltage = _safe_max(maxLowVoltage, lowVoltage)
@4000000063dc111c35d3711c   File "/data/BatteryAggregator/battery_service.py", line 70, in _safe_max
@4000000063dc111c35d384a4     return max(newValue, currentValue) if currentValue else newValue
@4000000063dc111c35d4f3d4 TypeError: '>' not supported between instances of 'float' and 'NoneType'
@4000000063dc111c3b45e1ac BatteryAggregator/setup: adding BatteryAggregator/setup to reinstallScriptsList
@4000000063dc111d0407de34 BatteryAggregator/setup: completed
***@***.***:~# reboot

**Comment by pulquero** [comment]
Thanks, fixed, v1.2.

**Comment by seamaster101** [comment]
Thank you I will test tonight and reportJordanOn Feb 2, 2023, at 16:32, pulquero ***@***.***> wrote:﻿
Thanks, fixed, v1.2.

**Comment by seamaster101** [comment]
Unfortunately the i tried too install it says “incompatible” and there is no install button

**Comment by pulquero** [comment]
Not sure why that would suddenly happen. Try running setup from the command line: "/data/BatteryAggregator/setup".

**Comment by seamaster101** [comment]
Yes
 That works now!


thank you! this is great!

**Comment by seamaster101** [comment]
Hi,I just updated DCBatteryAggregator to the latest version from the initial version I had. It was working with the initial version (1.0) and stopped working after the update. Can you please look at the possible issue? I’m running venusOS RPI large version v3.00~37JordanOn Feb 3, 2023, at 05:44, pulquero ***@***.***> wrote:﻿
Not sure why that would suddenly happen. Try running setup from the command line: "/data/BatteryAggregator/setup".

**Comment by pulquero** [comment]
Certainly, please attach the contents of the log.

**Comment by seamaster101** [comment]
Where do I find the log? I’m logged in and looking into data/batteryaggregator but don’t see log file thereJordanOn May 4, 2023, at 13:19, pulquero ***@***.***> wrote:﻿
Reopened #1.

**Comment by pulquero** [comment]
/var/log/BatteryAggregator/current

**Comment by seamaster101** [comment]
Here it ***@***.*** INFO:root:registered ourselves on D-Bus as ***@***.*** INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... ***@***.*** INFO:dbusmonitor:Found: com.victronenergy.battery.aggregator, scanning and storing ***@***.*** INFO:dbusmonitor:       com.victronenergy.battery.aggregator was skipped because it has no device ***@***.*** INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished ***@***.*** INFO:battery:Registered Battery ***@***.*** Traceback (most recent call ***@***.***   File "/data/BatteryAggregator/battery_service.py", line 148, in ***@***.***     ***@***.***   File "/data/BatteryAggregator/battery_service.py", line 144, in ***@***.***     self._local_values[alarm] = ***@***.*** KeyError: ***@***.*** INFO:dbusmonitor:Found: com.victronenergy.battery.ttyUSB0, scanning and storing ***@***.*** INFO:dbusmonitor:       com.victronenergy.battery.ttyUSB0 has device instance ***@***.*** BatteryAggregator/setup: ++ Installing Battery Aggregator ***@***.*** BatteryAggregator/setup: ++ Install Python library velib_python (master) from https://github.com/pulquero/velib_python into ***@***.*** BatteryAggregator/setup: restarting BatteryAggregator ***@***.*** BatteryAggregator/setup: completedJordanOn May 4, 2023, at 14:18, pulquero ***@***.***> wrote:﻿
/var/log/BatteryAggregator/current

**Comment by seamaster101** [comment]
Actually I noticed that you reopen the issue for the DCSystemAggregator. The issue is for BatteryAggregator not for DCSystemAggregator. For first time now I connected 2 BMSs. It will be good to try the aggregation parameters. I’m available for the next 3-4 hour to do some testing if you give me some instructions. JordanOn May 4, 2023, at 13:19, pulquero ***@***.***> wrote:﻿
Reopened #1.

**Comment by seamaster101** [comment]
![Uploading image.jpg…]()

**Comment by seamaster101** [comment]
I have a good news! I don’t know what happen (no changes were made anywhere) and after number of reboots it stated to display values and appears to work now! I have 2 x JKBMS connected. It is displaying some of the parameters but not others. I wonder if this is shortcomings in the SerialBattery implementation. I’m most interested to see the possible alarms raised by the BMS being reported e.g. cell voltage more than x, cell voltage less than x, cell delta more than x etc. Is that something you can give me some instructions how to setup?JordanOn May 4, 2023, at 14:18, pulquero ***@***.***> wrote:﻿
/var/log/BatteryAggregator/current

**Comment by pulquero** [comment]
Looks like it upgraded to a newer version. To see all the parameters, run dbus-spy, and attach a screenshot for the BMSes. I can then try to add them to the aggregator.
